[platformio]
src_dir = hackerspacemap2026/

[env:esp32c3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board = esp32-c3-devkitm-1
board_build.mcu = esp32c3
framework = arduino
upload_protocol = esptool

build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DARDUINO_TINYUSB=1
  -DCORE_DEBUG_LEVEL=5  ; Set the debug level (0-5, with 5 being the most verbose)
